---
- hosts: agents
  remote_user: root
  vars:
    ansible_become_pass: "{{ ansible_ssh_pass }}"
  vars_files:
    - vault
  become: yes
  become_method: sudo

  roles:
    - role: adjust-vimrc
    - role: adjust-term
    - role: upgrade-os
    - role: python-pkgs
