---
- name: add deploying user to remote
  ansible.builtin.user:
    state: present
    name: "{{ target_user }}"
    password: "{{ target_secret | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    comment: ansible user
    groups:
      - sudo
    shell: /bin/bash
  tags:
    - deployuser
...
